---
title: "Lab4_Group10"
author: "Jiayi Guo, Panyi Liu, Xiangning Dong"
date: "2022-11-09"
output: html_document
---

## [Github Repository](https://github.com/AndrewGuo525/Lab4)
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## LoadPackage
```{r message=FALSE,warning=FALSE}
library(datasets)
library(tidyverse)
library(fields)
library(janitor)
```

## Problem 1
```{r}
k_means <- function(data, k, iter){
  set.seed(111)
  
  data <- data %>% 
    mutate(label = sample(1:k, 150, replace = T)) # Randomly assigning each observation to a cluster
  
  centroids <- data %>% # Calculate the centroids for each of the cluster
    group_by(label) %>% 
    summarise(centr <- across(everything(),mean)) %>% 
    select(-label)
  
  for(i in seq_len(iter)){
    # Calculate the distance from each point to each of the centroids 
     dist <- rdist(centroids, data[,-5])
       
    # Calculate the minimum distance for each point to the centroids
     data <- data %>% 
       mutate(label = apply(dist, 2, which.min))
    
    # Calculate the new centroids
    centroids <- data %>% # Calculate the centroids for each of the cluster
      group_by(label) %>% 
      summarise(centr <- across(everything(),mean)) %>% 
      select(-label)
  }
  return(data$label)
}
```

## Problem 2
```{r}
set.seed(111)
library(datasets)
## Scale the data
iris_scaled <- iris %>% select(c(1:4))
iris_scaled <- as.data.frame(scale(iris_scaled))

cluster_iris <- k_means(iris_scaled, k = 3, iter = 50)
iris_scaled <- iris_scaled %>%
  mutate(cluster = cluster_iris)


## Visualization
ggpairs(iris_scaled, columns = 1:4, ggplot2::aes(colour=as.factor(cluster), alpha=0.5))
```

## Problem 3
```{r}
## Set a seed
set.seed(111)  

## Define function to calculate the total within-cluster sum of square
wss <- function(k, data) {
  kmeans(data, k, nstart = 50)$tot.withinss
}

## Get the total within-cluster sum of square for each k
k <- 1:15  
wSS <- map_dbl(k, wss, data = iris_scaled)
wss_table <- data.frame(wss = wSS, k = k)

## Plot the value corresponding to each k
ggplot(wss_table, aes(x = k, y = wSS)) + 
  geom_point() +  
  geom_line() +
  labs(x = "Cluster Size",
       y = "Total Within-cluster Sum of Squares",
       title = "Elbow Plot")
```



